name: 'GitHub Subtree Push'
description: 'Pushing to a GitHub repository subtree local changes'
author: 'jbrooksuk'
branding:
  icon: upload-cloud
  color: green
inputs:
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  repository:
    description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: ''
    required: false
  branch:
    description: 'Destination branch to push changes'
    required: false
    default: 'master'
  directory:
    description: 'Directory to change to before pushing.'
    required: false
    default: '.'
  publish_directory:
    description: 'Directory of contents to push.'
    required: true
    default: '.'
    
runs:
  using: 'node12'
  main: 'start.js'
